{"name": "test_error_cases[5-xyz-multiply-\\u041d\\u0435\\u043a\\u043e\\u0440\\u0440\\u0435\\u043a\\u0442\\u043d\\u044b\\u0439 \\u0444\\u043e\\u0440\\u043c\\u0430\\u0442 \\u0447\\u0438\\u0441\\u043b\\u0430]", "status": "passed", "steps": [{"name": "Открываем и заполняем форму с ошибками", "status": "passed", "start": 1738868331142, "stop": 1738868331604}, {"name": "Проверяем сообщение об ошибке", "status": "passed", "start": 1738868332615, "stop": 1738868332640}], "parameters": [{"name": "num1", "value": "5"}, {"name": "num2", "value": "'xyz'"}, {"name": "operation", "value": "'multiply'"}, {"name": "expected_error", "value": "'Некорректный формат числа'"}], "start": 1738868331142, "stop": 1738868332640, "uuid": "af3e04df-e157-4faf-adde-ea645e456d62", "historyId": "1fa45810e007512529df3e2880351421", "testCaseId": "938b571ad6ce813f24f8a764b084d3a2", "fullName": "tests.test_calculator.TestAdvancedCalculator#test_error_cases", "labels": [{"name": "story", "value": "Проверка обработки ошибок"}, {"name": "feature", "value": "Тесты калькулятора"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestAdvancedCalculator"}, {"name": "host", "value": "anton"}, {"name": "thread", "value": "28068-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_calculator"}]}